#spring.application.name=profiles-service
#eureka.client.serviceUrl.defaultZone:http://localhost:8761/eureka/
server.port=8098

spring.jpa.hibernate.ddl-auto=none

#spring.datasource.url=jdbc:postgresql://ec2-52-214-82-153.eu-west-1.compute.amazonaws.com:5432/d93icrectkr0s5
#spring.datasource.username=ubhvhg6k11glmr
#spring.datasource.password=pfa4b197e0b1433351d8ca47ac07643186008a92f07439c1f4ca5c77c08357489

spring.datasource.url=jdbc:postgresql://localhost:5432/codersden
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

bst.r2.bucket=bst-bucket
bst.r2.account=f1be7a5fb0d5edf4a3f9ece40450b1e1
bst.r2.accessKey=6866013c5233ebf815083ab291227b19
bst.r2.secretKey=ada22ca40cdf56ec875ae05dd47e2e4c7139fd6c67ff9320123fedebbaa3cc8c
bst.r2.publicDomain=https://pub-0c72344395a2464daa65bb426d55a991.r2.dev
#stripe.secret-key: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
stripe.secret-key: sk_test_51QkU8tCZwUNvHoeI9pj8f4dkZFlDAubbYSzkqbQsSKwE0JbTnPn6IZMPz6lVuMkrfvGPufzAgI3OYbjKwmWyOHja00INESdXVY
